# -------------- 基础：官方已瘦身 JRE --------------
FROM openjdk:17-slim

# 安装 docker-cli 与 mysqldump
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        docker.io \
        default-mysql-client; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
           /usr/share/doc/* /usr/share/man/* /usr/share/info/*

WORKDIR /app
COPY sys.jar /app/
RUN chmod +x /app/sys.jar

ENV JAVA_OPTS="-Xms256m -Xmx512m -XX:+UseContainerSupport"
EXPOSE 2121
CMD ["sh", "-c", "exec java $JAVA_OPTS -jar /app/sys.jar"]
